#!/usr/bin/env bash

docker kill $(docker ps -q)
docker run -e SERVER_PORT=42069 -e SERVER_STYLE=$1 -d --rm -it -p 42069:42069 ts-ws-test
sleep 1
node=$(pgrep node)

echo "./measure $node $($((60*4))) $2"
./measure $node $((60*4)) $2

docker kill $(docker ps -q)

