#!/usr/bin/env bash

docker kill $(docker ps -q)
docker run -e SERVER_PORT=42069 -d --rm -it -p 42069:42069 $1-game-test
sleep 1
pid=$(pgrep server || pgrep main)
echo "I GOT PID $pid"
time=$3

if [ -z $time ]; then
                $time=$((60*4))
fi

echo "./measure $pid $($((60*4))) $2"
./measure $pid $time $2

docker kill $(docker ps -q)



