#!/usr/bin/env bash
count=$(echo $GAME_COUNT || $1)
conn=$(echo $CONN || $2)
type=$(echo $TYPE || $3)

set -x
cargo run --release --bin game_player $count --connections $conn --host events.theprimeagen.tv | tee ../video-3/c.$type.$count.res
scp root@events.theprimeagen.tv:/root/tyrone-biggums/c.$type.$count ../video-3/c.$type.$count
set +x

