#!/usr/bin/env bash
cargo run --release --bin game_player $1 $([[ ! -z $4 ]] && echo "--time $4") --connections $2 --host events.theprimeagen.tv | tee ../video-3/c.$3.$2.res
scp root@events.theprimeagen.tv:/root/tyrone-biggums/c.$3.$2 ../video-3/c.$3.$2

